export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function ChatAssistantLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <div>
        {children}
        </div>
  )
}
